names = ['ken', 'davin', 'eric', 'kristin', 'john', 'mom', 'dad', 'parker', 'holden', 'audry']
print(names)
print(names[0])
print(names[0].title())
print(names[1].title())
print(names[2].title())
print(names[3].title())
print(names[4].title())
print(names[5].title())
print(names[6].title())
print(names[7].title())
print(names[8].title())
print(names[9].title())
